spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

coolsms:
  api:
    key: NCSYTNABNR7FXQHU
    secret: CJAPKFHGAKJTHDBNJBNIZITEQUMPZ7C8
    number: 01095554380